export type SurpriseCadence = 'daily' | 'weekly' | 'monthly';

export interface SurpriseIdea {
  key: string;
  title: string;
  description: string;
  vibe: string;
  effort: string;
}

export const SURPRISE_IDEAS: Record<SurpriseCadence, SurpriseIdea[]> = {
  daily: [
    {
      key: 'daily-breakfast-note',
      title: 'Breakfast Note Upgrade',
      description: 'Leave a handwritten note beside her breakfast with one specific thing you adore about her today.',
      vibe: 'Soft and personal',
      effort: '10 minutes',
    },
    {
      key: 'daily-pocket-sweets',
      title: 'Tiny Pocket Treat',
      description: 'Hide a small snack, chocolate, or tea she likes with a tag that says “for later, when you need a boost.”',
      vibe: 'Cute and useful',
      effort: '10 minutes',
    },
    {
      key: 'daily-voice-letter',
      title: 'Mini Voice Letter',
      description: 'Record a short voice note telling her your favorite moment from this week and send it when she least expects it.',
      vibe: 'Warm and intimate',
      effort: '5 minutes',
    },
    {
      key: 'daily-bathroom-mirror',
      title: 'Mirror Compliment',
      description: 'Write a sweet message on the bathroom mirror so she finds it while getting ready.',
      vibe: 'Playful and romantic',
      effort: '5 minutes',
    },
    {
      key: 'daily-lunch-upgrade',
      title: 'Lunch Upgrade',
      description: 'Add one extra thoughtful thing to her lunch or snack bag: fruit cut nicely, a dessert, or a tiny note.',
      vibe: 'Caring',
      effort: '15 minutes',
    },
    {
      key: 'daily-music-drop',
      title: 'Private Song Drop',
      description: 'Send her one song with a one-line reason it made you think of her.',
      vibe: 'Tender',
      effort: '5 minutes',
    },
    {
      key: 'daily-photo-memory',
      title: 'One-Photo Memory',
      description: 'Send one old photo of you two with a caption about why that moment still matters to you.',
      vibe: 'Nostalgic',
      effort: '10 minutes',
    },
    {
      key: 'daily-desk-surprise',
      title: 'Desk Surprise',
      description: 'Leave a tiny flower, snack, or folded note where she will discover it during the day.',
      vibe: 'Sweet',
      effort: '10 minutes',
    },
    {
      key: 'daily-compliment-list',
      title: 'Three Specific Compliments',
      description: 'Write three very specific compliments about how she looks, thinks, or cares for people.',
      vibe: 'Affectionate',
      effort: '10 minutes',
    },
    {
      key: 'daily-tea-ready',
      title: 'Tea or Coffee Ready',
      description: 'Prepare her favorite drink exactly how she likes it and bring it with a smile and no commentary.',
      vibe: 'Gentle',
      effort: '10 minutes',
    },
    {
      key: 'daily-sunset-invite',
      title: 'Sunset Walk Invite',
      description: 'Invite her on a short walk at golden hour with the only agenda being holding hands and talking.',
      vibe: 'Simple romance',
      effort: '20 minutes',
    },
    {
      key: 'daily-favorite-order',
      title: 'Favorite Order Rescue',
      description: 'Bring home her go-to pastry, drink, or snack without her needing to ask for it.',
      vibe: 'Thoughtful',
      effort: '15 minutes',
    },
    {
      key: 'daily-compliment-reminder',
      title: 'Phone Wallpaper Note',
      description: 'Make a tiny lock-screen style image with a sweet line just for her and send it over.',
      vibe: 'Cute techy romance',
      effort: '10 minutes',
    },
    {
      key: 'daily-hero-task',
      title: 'Invisible Hero Move',
      description: 'Quietly handle one annoying small task she dislikes, then tell her only after it is done.',
      vibe: 'Relieving',
      effort: '15 minutes',
    },
  ],
  weekly: [
    {
      key: 'weekly-at-home-date',
      title: 'At-Home Date Night Reset',
      description: 'Transform one evening with candles, a proper drink, music, and one planned activity instead of default sofa mode.',
      vibe: 'Romantic and intentional',
      effort: '1 hour',
    },
    {
      key: 'weekly-mini-scavenger',
      title: 'Mini Scavenger Trail',
      description: 'Set up 3 to 5 small clues around the house leading to a snack, flower, or little gift.',
      vibe: 'Cute and playful',
      effort: '45 minutes',
    },
    {
      key: 'weekly-favorite-things-box',
      title: 'Favorite Things Box',
      description: 'Put together a mini box with two or three things she loves: a snack, face mask, tea, note, or tiny trinket.',
      vibe: 'Pampering',
      effort: '45 minutes',
    },
    {
      key: 'weekly-golden-hour-picnic',
      title: 'Golden Hour Picnic',
      description: 'Pack a simple picnic and take her somewhere calm for an hour outdoors with good snacks and a blanket.',
      vibe: 'Dreamy',
      effort: '1.5 hours',
    },
    {
      key: 'weekly-dessert-run',
      title: 'Late Dessert Adventure',
      description: 'Take her out unexpectedly just for dessert, tea, or hot chocolate somewhere cosy.',
      vibe: 'Light and flirtatious',
      effort: '1 hour',
    },
    {
      key: 'weekly-memory-envelope',
      title: 'Memory Envelope',
      description: 'Write a short letter about one memory you never want to lose and give it to her sealed.',
      vibe: 'Deep and sentimental',
      effort: '30 minutes',
    },
    {
      key: 'weekly-bath-spa',
      title: 'Spa Night Setup',
      description: 'Set up a proper bath or shower reset with towels ready, skincare, music, and her favorite treat afterwards.',
      vibe: 'Luxury at home',
      effort: '40 minutes',
    },
    {
      key: 'weekly-breakfast-date',
      title: 'Breakfast Date Out',
      description: 'Take her on a morning date for pastries, coffee, and a slow start before the day gets noisy.',
      vibe: 'Soft weekend energy',
      effort: '2 hours',
    },
    {
      key: 'weekly-polaroid-start',
      title: 'Start a Tiny Photo Series',
      description: 'Take one intentional photo of the two of you and start a little series with captions.',
      vibe: 'Keepsake',
      effort: '30 minutes',
    },
    {
      key: 'weekly-favorite-cook',
      title: 'Cook Her Favorite Properly',
      description: 'Make one of her favorite meals as if it were an occasion, with plating and the table done nicely.',
      vibe: 'Comfort and care',
      effort: '1.5 hours',
    },
    {
      key: 'weekly-rainy-drive',
      title: 'Rainy Drive Date',
      description: 'Go on a short drive with her favorite playlist, pick up drinks, and just talk.',
      vibe: 'Movie-scene cute',
      effort: '1 hour',
    },
    {
      key: 'weekly-flower-stem',
      title: 'Single Beautiful Stem',
      description: 'Bring her one really beautiful flower with an actual reason you chose it.',
      vibe: 'Elegant',
      effort: '20 minutes',
    },
    {
      key: 'weekly-secret-reservation',
      title: 'Secret Reservation',
      description: 'Book something low-stress but lovely for you both and only reveal the dress code and time.',
      vibe: 'Exciting',
      effort: '45 minutes',
    },
    {
      key: 'weekly-three-reasons-date',
      title: 'Three Reasons Date',
      description: 'Plan a short date themed around three reasons you love her, and tell her each one during the date.',
      vibe: 'Cheesy in the right way',
      effort: '1 hour',
    },
  ],
  monthly: [
    {
      key: 'monthly-mystery-day',
      title: 'Mystery Day Out',
      description: 'Plan half a day with two or three stops she will love and reveal each one only when you arrive.',
      vibe: 'Cute and amazing',
      effort: 'Half day',
    },
    {
      key: 'monthly-love-letter-kit',
      title: 'Love Letter and Gift Pairing',
      description: 'Write a proper letter and pair it with one thoughtful gift that clearly shows you noticed something about her lately.',
      vibe: 'Deeply romantic',
      effort: '2 to 3 hours',
    },
    {
      key: 'monthly-sunset-dinner',
      title: 'Sunset Dinner Setup',
      description: 'Create a full dinner moment at home or outdoors with candles, nice plating, music, and dessert.',
      vibe: 'Movie-level romance',
      effort: '3 hours',
    },
    {
      key: 'monthly-memory-box',
      title: 'Memory Box Drop',
      description: 'Put together a box with printed photos, a note, ticket stubs, tiny mementos, or a shared playlist QR card.',
      vibe: 'Keepsake magic',
      effort: '2 hours',
    },
    {
      key: 'monthly-adventure-booking',
      title: 'Book a Real Experience',
      description: 'Book something worth getting dressed for: pottery, a class, a tasting, a boat ride, or another experience she would genuinely remember.',
      vibe: 'Amazing and intentional',
      effort: '2 hours',
    },
    {
      key: 'monthly-bedroom-transform',
      title: 'Bedroom Reset Surprise',
      description: 'Refresh the room with fresh sheets, soft lighting, her favorite scent, snacks, and a note for a full cosy-night reveal.',
      vibe: 'Luxury and care',
      effort: '2 hours',
    },
    {
      key: 'monthly-micro-trip',
      title: 'Micro Trip Planning',
      description: 'Plan a one-night escape or full-day trip and present it like a little invitation.',
      vibe: 'Big romantic energy',
      effort: 'Planning heavy',
    },
    {
      key: 'monthly-story-date',
      title: 'Date Built Around Your Story',
      description: 'Design a date using places, food, music, or jokes from your relationship so it feels unmistakably “you two.”',
      vibe: 'Personal and unforgettable',
      effort: '2 to 4 hours',
    },
    {
      key: 'monthly-photo-session',
      title: 'Personal Photo Session',
      description: 'Take her somewhere pretty, dress up a little, and make a small date around taking intentional photos together.',
      vibe: 'Romantic main-character',
      effort: 'Half day',
    },
    {
      key: 'monthly-pamper-evening',
      title: 'Full Pamper Evening',
      description: 'Give her an evening that feels designed around comfort: dinner ready, bath ready, skincare, soft clothes, dessert, and zero stress.',
      vibe: 'Adoring',
      effort: '2 hours',
    },
    {
      key: 'monthly-scrapbook-page',
      title: 'Handmade Scrapbook Page',
      description: 'Make one beautiful scrapbook page or card about your month together and give it to her properly.',
      vibe: 'Handmade romance',
      effort: '2 hours',
    },
    {
      key: 'monthly-surprise-picnic-drive',
      title: 'Surprise Scenic Picnic',
      description: 'Drive her somewhere scenic with good food ready and a plan for sunset or stargazing afterwards.',
      vibe: 'Cute and amazing',
      effort: 'Half day',
    },
    {
      key: 'monthly-favorite-things-date',
      title: 'Favorite Things Date',
      description: 'Build an evening using only things she loves: her snack, her drink, her film genre, her flowers, her music.',
      vibe: 'Seen and cherished',
      effort: '2 hours',
    },
    {
      key: 'monthly-restaurant-dressup',
      title: 'Dress-Up Dinner Reservation',
      description: 'Book somewhere genuinely nice, tell her to dress beautifully, and make the whole evening feel like a special occasion.',
      vibe: 'Classic romance',
      effort: 'Evening',
    },
  ],
};

export const SURPRISE_CADENCE_LABELS: Record<SurpriseCadence, string> = {
  daily: 'Every day',
  weekly: 'Once a week',
  monthly: 'Once a month',
};

export const SURPRISE_CADENCE_WINDOWS: Record<SurpriseCadence, { label: string; milliseconds: number }> = {
  daily: { label: '24 hours', milliseconds: 24 * 60 * 60 * 1000 },
  weekly: { label: '7 days', milliseconds: 7 * 24 * 60 * 60 * 1000 },
  monthly: { label: '30 days', milliseconds: 30 * 24 * 60 * 60 * 1000 },
};
